"""empty message

Revision ID: 430bfc421a38
Revises: 
Create Date: 2023-01-10 14:17:56.230314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430bfc421a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuijian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_team', sa.String(length=64), nullable=True),
    sa.Column('guest_team', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=32), nullable=True, comment='开始时间'),
    sa.Column('result', sa.Boolean(), nullable=True, comment='预测结果'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuijian')
    # ### end Alembic commands ###
